name: "mysql2sqlite CI"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@master
      - name: "WHEREAMI"
        run: pwd
      - name: "LIST"
        run: ls -lah
      - name: "Run unit tests"
        run: bash ./unit_tests.sh
