name: "mysql2sqlite CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Run unit tests"
        run: bash unit_tests.sh
